[project]
name = "gradchecklist"
description = "Graduation checklist flask application."
version = "0.0.0"
dependencies = [
    "flask"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
