[project]
name = "gradchecklist"
description = "Module checker Flask application."
dynamic = ["version"]
dependencies = [
    "flask"
]

[build-system]
requires = ["flit_core >=3.2"]
build-backend = "flit_core.buildapi"
